# Generated by Django 2.2.7 on 2019-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assunto', models.CharField(blank=True, max_length=50)),
                ('Pergunta', models.CharField(blank=True, max_length=50)),
                ('Resposta', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
