# Generated by Django 2.2.7 on 2019-12-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20191203_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsform',
            name='Assunto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelsform',
            name='Pergunta',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelsform',
            name='Resposta',
            field=models.TextField(max_length=50),
        ),
    ]
