# Generated by Django 2.2.7 on 2019-12-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20191203_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsform',
            name='Pergunta',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='modelsform',
            name='Resposta',
            field=models.TextField(max_length=1000),
        ),
    ]
