# Generated by Django 2.2.7 on 2019-12-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20191204_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modelsForm',
            new_name='ModeloFormulario',
        ),
    ]
