# Generated by Django 2.2.7 on 2019-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20191205_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloformulario',
            name='Checkbox',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='modeloformulario',
            name='Assunto',
            field=models.CharField(choices=[('INFORMAÇÃO DA EMPRESA', 'INFORMAÇÃO DA EMPRESA'), ('IMFORMAÇÃO DE CONTATO', 'IMFORMAÇÃO DE CONTATO'), ('INFORMAÇÃO DO LOCAL', 'INFORMAÇÃO DO LOCAL'), ('INFORMAÇÃO DO PRODUTO', 'INFORMAÇÃO DO PRODUTO'), ('COMUNICAÇÃO FORA DE CONTEXTO', 'COMUNICAÇÃO FORA DE CONTEXTO')], max_length=50),
        ),
    ]
