# Generated by Django 2.2.7 on 2019-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20191210_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloformulario',
            name='Checkbox',
        ),
        migrations.AlterField(
            model_name='modeloformulario',
            name='Assunto',
            field=models.CharField(choices=[('ask_faq/kyros', 'INFORMAÇÃO DA EMPRESA'), ('ask_faq/owners_kyros', 'INFORMA PROPRIETÁRIOS'), ('ask_faq/foundation', 'INFORMA FUNDAÇÃO'), ('ask_faq/services', 'INFORMA OS SERVIÇOS'), ('ask_faq/projects', 'INFORMA OS PROJETOS'), ('ask_faq/products', 'INFORMA PRODUTOS'), ('ask_faq/kyros_vision', 'INFORMA VISÃO DA EMPRESA'), ('ask_faq/kyros_values', 'INFORMA VALORES'), ('ask_faq/kyros_address', 'INFORMA ENDEREÇO'), ('ask_faq/kyros_contact', 'INFORMA CONTATO'), ('ask_faq/kyros_email', 'INFORMA EMAIL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeloformulario',
            name='Pergunta',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='modeloformulario',
            name='Resposta',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
