# Generated by Django 2.0 on 2019-12-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20191230_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeloFormulario',
            new_name='ModelFormulario',
        ),
    ]
